class_name Enums

enum EffectTrigger {
	ON_PLAY,
	ON_DRAW,
	ON_DISCARD,
	ON_TURN_START,
	ON_TURN_END,
	ON_COMBAT_START,
	ON_COMBAT_END,
	ON_DAMAGE_DEALT,
	ON_DAMAGE_TAKEN,
	ON_ENEMY_DEFEATED,
	ON_WORD_FORMED,
	ON_NOVEL_WORD,
	ON_POS_MATCH,
	ON_AFFIX_ATTACHED,
	PASSIVE,
	INTERCEPTOR,
}

enum POSType { NOUN, VERB, ADJECTIVE, ADVERB, DETERMINER, PREPOSITION }

enum MorphemeFamily { GERMANIC, LATINATE, GREEK, FUNCTIONAL }

enum GraphemeFamily { LATIN, RUNIC, GREEK, CJK }

enum ActionType {
	DEAL_DAMAGE,
	GAIN_INSULATION,
	DRAW_MORPHEME,
	DISCARD_MORPHEME,
	GAIN_SEMANT,
	LOSE_COGENCY,
	HEAL_COGENCY,
	ADD_MULTIPLIER,
}
